/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "includes.h"
#include "app.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0      (GUI_ID_USER + 0x00)
#define ID_TEXT_SQUARE       (GUI_ID_USER + 0x01)
#define ID_TEXT_fWLOAD      (GUI_ID_USER + 0x02)
#define ID_TEXT_STDLEN      (GUI_ID_USER + 0x03)
#define ID_TEXT_G      (GUI_ID_USER + 0x04)
#define ID_TEXT_TIMEUSE      (GUI_ID_USER + 0x05)

#define ID_EDIT_SQUARE		 (GUI_ID_USER + 0x06)
#define ID_EDIT_fWLOAD      (GUI_ID_USER + 0x07)
#define ID_EDIT_STDLEN       (GUI_ID_USER + 0x08) 
#define ID_EDIT_G      (GUI_ID_USER + 0x09)
#define ID_EDIT_TIMEUSE		 (GUI_ID_USER + 0x0A)

#define ID_TEXT_USQUARE      (GUI_ID_USER + 0x0E)
#define ID_TEXT_UfWLOAD      (GUI_ID_USER + 0x0F)
#define ID_TEXT_USTDLEN      (GUI_ID_USER + 0x10)
#define ID_TEXT_UG      (GUI_ID_USER + 0x11)
#define ID_TEXT_UTIMEUSE       (GUI_ID_USER +  0x12)

#define ID_BUTTON_SAVE      (GUI_ID_USER + 0x14)
#define ID_BUTTON_CANCEL      (GUI_ID_USER + 0x15)
#define ID_BUTTON_NEXT      (GUI_ID_USER + 0x16)

extern CONFIG_DATA_U __configDataU;
extern SAMPLE_SAVE_INFO __sampleInfo;

// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreateCh[] = {
  { FRAMEWIN_CreateIndirect, "试样信息", ID_FRAMEWIN_0,  0, 0, 800, 480, GUI_TA_HCENTER | GUI_TA_VCENTER, 0x0, 0 },
  
  { TEXT_CreateIndirect, "面积", ID_TEXT_SQUARE, 130, 60, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "力量宽度", ID_TEXT_fWLOAD, 130, 120, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "标距", ID_TEXT_STDLEN, 130, 180, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "克重", ID_TEXT_G, 130, 240, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "时间", ID_TEXT_TIMEUSE, 130, 300, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
 
  { EDIT_CreateIndirect, "Edit4", ID_EDIT_SQUARE, 300, 60, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit0", ID_EDIT_fWLOAD, 300, 120, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit1", ID_EDIT_STDLEN, 300, 180, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit2", ID_EDIT_G, 300, 240, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit3", ID_EDIT_TIMEUSE, 300, 300, 80, 30, 0, 0x64, 0 },

  
  { TEXT_CreateIndirect, "mm^2", ID_TEXT_USQUARE, 380, 60, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "mm", ID_TEXT_UfWLOAD, 380, 120, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "N", ID_TEXT_USTDLEN, 380, 180, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "G", ID_TEXT_UG, 380, 240, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "s", ID_TEXT_UTIMEUSE, 390, 300, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },

//  { BUTTON_CreateIndirect, "上", ID_BUTTON_UP, 575, 110, 80, 50, 0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "下", ID_BUTTON_DOWN, 575, 250, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "保存", ID_BUTTON_SAVE, 0, 368, 266, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "取消", ID_BUTTON_CANCEL, 266, 368, 266, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "下一步", ID_BUTTON_NEXT, 532, 368, 266, 80, 0, 0x0, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

static const GUI_WIDGET_CREATE_INFO _aDialogCreateEn[] = {
  { FRAMEWIN_CreateIndirect, "Sample Info", ID_FRAMEWIN_0,  0, 0, 800, 480, GUI_TA_HCENTER | GUI_TA_VCENTER, 0x0, 0 },
  
  { TEXT_CreateIndirect, "Square", ID_TEXT_SQUARE, 130, 60, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "Width Loaded", ID_TEXT_fWLOAD, 130, 120, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "Standart Lenth", ID_TEXT_STDLEN, 130, 180, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "g", ID_TEXT_G, 130, 240, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
  { TEXT_CreateIndirect, "Time", ID_TEXT_TIMEUSE, 130, 300, 120, 30, GUI_TA_RIGHT | GUI_TA_VCENTER, 0x0, 0 },
 
  { EDIT_CreateIndirect, "Edit4", ID_EDIT_SQUARE, 300, 60, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit0", ID_EDIT_fWLOAD, 300, 120, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit1", ID_EDIT_STDLEN, 300, 180, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit2", ID_EDIT_G, 300, 240, 80, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit3", ID_EDIT_TIMEUSE, 300, 300, 35, 30, 0, 0x64, 0 },

  
  { TEXT_CreateIndirect, "mm^2", ID_TEXT_USQUARE, 380, 60, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "mm", ID_TEXT_UfWLOAD, 380, 120, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "N", ID_TEXT_USTDLEN, 380, 180, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "G", ID_TEXT_UG, 380, 240, 120, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
  { TEXT_CreateIndirect, "s", ID_TEXT_UTIMEUSE, 340, 300, 20, 30, GUI_TA_LEFT | GUI_TA_TOP, 0x0, 0 },
//  { BUTTON_CreateIndirect, "上", ID_BUTTON_UP, 575, 110, 80, 50, 0, 0x0, 0 },
 // { BUTTON_CreateIndirect, "下", ID_BUTTON_DOWN, 575, 250, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Save", ID_BUTTON_SAVE, 0, 368, 266, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_CANCEL, 266, 368, 266, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next", ID_BUTTON_NEXT, 532, 368, 266, 80, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char strBuffer[30];
  float EditBuffer;
  unsigned char testType;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 32);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);	
	FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,5);
	////Loading and setting old data;
	testType = 	__configDataU.testMethodLaOrYa;

	sprintf(strBuffer,"%.2f",__sampleInfo.square[testType]);
	EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_SQUARE),strBuffer);

	sprintf(strBuffer,"%.2f",__sampleInfo.fWidthLoaded[testType]);
	EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_fWLOAD),strBuffer);

	sprintf(strBuffer,"%.2f",__sampleInfo.StandartLen);
	EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_STDLEN),strBuffer);

	sprintf(strBuffer,"%.2f",__sampleInfo.g);
	EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_G),strBuffer);


	sprintf(strBuffer,"%d",__sampleInfo.timeWillUsed);
	EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_TIMEUSE),strBuffer);


    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_fWLOAD: // Notifications sent by 'Edit0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, ID_EDIT_fWLOAD),3);
		break;
      }
      break;
    case ID_EDIT_STDLEN: // Notifications sent by 'Edit1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, ID_EDIT_STDLEN),3);	
        break;
      }
      break;
    case ID_EDIT_G: // Notifications sent by 'Edit2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, ID_EDIT_G),3);
        break;
      }
      break;
    case ID_EDIT_TIMEUSE: // Notifications sent by 'Edit3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, ID_EDIT_TIMEUSE),1);
        break;
      }
      break;
	 case ID_EDIT_SQUARE: // Notifications sent by 'Edit4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        KeyPad_Interface(WM_GetDialogItem(pMsg->hWin, ID_EDIT_SQUARE),3);
        break;
      }
      break;
    case ID_BUTTON_SAVE: // Notifications sent by 'SAVE'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
		  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_SQUARE), strBuffer, 30);
		  EditBuffer = atof(strBuffer);
		  SAMPLE_Set_square(EditBuffer);

		  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_fWLOAD), strBuffer, 30);
		  EditBuffer = atof(strBuffer);
		  SAMPLE_Set_fWidthLoaded(EditBuffer);

		  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_STDLEN), strBuffer, 30);
		  EditBuffer = atof(strBuffer);
		  SAMPLE_Set_StandartLen(EditBuffer);

		  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_G), strBuffer, 30);
		  EditBuffer = atof(strBuffer);
		  SAMPLE_Set_g(EditBuffer);

		  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_TIMEUSE), strBuffer, 30);
		  EditBuffer = atoi(strBuffer);
		  SAMPLE_Set_timeWillUsed(EditBuffer);


		  __CloseWindows(pMsg);

        break;
      }
      break;
    case ID_BUTTON_CANCEL: // Notifications sent by 'CANCEL'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
		__CloseWindows(pMsg);

        break;
      }
      break;
    case ID_BUTTON_NEXT: // Notifications sent by 'NextStep'
      switch(NCode) {

      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
	}
    break;
  default:
    WM_DefaultProc(pMsg); 
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       SampleInfo
*/
static WM_HWIN SampleInfo(void);
static WM_HWIN SampleInfo(void) {
  WM_HWIN hWin;

   if(__configDataU.languageSel == 0){
		BUTTON_SetDefaultFont(&GUI_Font20HZK);
		TEXT_SetDefaultFont(&GUI_Font20HZK);
		FRAMEWIN_SetDefaultFont(&GUI_Font20HZK);
		EDIT_SetDefaultFont(&GUI_Font20HZK);
		hWin = GUI_CreateDialogBox(_aDialogCreateCh, GUI_COUNTOF(_aDialogCreateCh), _cbDialog, WM_HBKWIN, 0, 0);
	   }
  else if(__configDataU.languageSel == 1){
		BUTTON_SetDefaultFont(&GUI_Font20HZKF);
		TEXT_SetDefaultFont(&GUI_Font20HZKF);
		FRAMEWIN_SetDefaultFont(&GUI_Font20HZKF);
		EDIT_SetDefaultFont(&GUI_Font20HZKF);
		hWin = GUI_CreateDialogBox(_aDialogCreateCh, GUI_COUNTOF(_aDialogCreateCh), _cbDialog, WM_HBKWIN, 0, 0);
		}
  else {
		FRAMEWIN_SetDefaultFont(GUI_FONT_16B_1);
		BUTTON_SetDefaultFont(GUI_FONT_16B_1);
		TEXT_SetDefaultFont(GUI_FONT_32B_1);
		EDIT_SetDefaultFont(GUI_FONT_32B_1);
		hWin = GUI_CreateDialogBox(_aDialogCreateEn, GUI_COUNTOF(_aDialogCreateEn), _cbDialog, WM_HBKWIN, 0, 0);
		}
  return hWin;
}

unsigned int FUN_ICON3Clicked(void)
{

	SampleInfo();
	return 0xFF;

	
}
